# Generated by Django 2.1.4 on 2018-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
