# Generated by Django 2.1.4 on 2019-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentposition',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
