# Generated by Django 2.1.4 on 2019-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190122_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentposition',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='done',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
